config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/home", to: "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"

    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = Settings.valid_email_regex
  
  before_save{email.downcase!}
  
  validates :name, presence: true, length: {maximum: Settings.maximum_name}
  validates :email, presence: true,
    length: {maximum: Settings.maximum_email_length},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: true
  validates :password, presence: true,
    length: {minimum: Settings.minimum_pass_length}
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    private
    def set_locale
      locale = params[:locale].to_s.strip.to_sym
      check = I18n.available_locales.include?(locale)
      I18n.locale = check ? locale : I18n.default_locale
    end
  
    def default_url_options
      {locale: I18n.locale}
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    return if @user = User.find_by(id: params[:id])

    flash[:danger] = t "not_found"
    redirect_to root_url
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash.now[:success] = t "welcome_sample_app"
      redirect_to @user
    else
      flash.now[:danger] = t "not_success"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title page_title
      base_title = I18n.t "ruby_on_rails_tutorial_sample_app"
      if page_title.blank?
        base_title
      else
        page_title + " | " + base_title
      end
    end
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.size
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "the" %> <%= link_to t("ruby_on_rails_tutorial"), Settings.railstutorials_org %>
    <%= t "by" %> <%= link_to "Michael Hartl", Settings.author %>
  </small>
  <nav>
    <ul>
      <li> <%= link_to t("about"), about_path %> </li>
      <li> <%= link_to t("contact"), contact_path %> </li>
      <li> <%= link_to t("news"), Settings.news_railstutorial %> </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), home_path %></li>
        <li><%= link_to t("help"), help_path %></li>
        <li><%= link_to t("login"), "#" %></li>
        <%= link_to t("en"), locale: "en" %>
        <%= link_to t("vi"), locale: "vi" %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div  class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "the_form_contains" %><%= pluralize(@user.errors.size, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, t("about") %>
<h1><%= t "about" %></h1>
<p>
  <%= t "the" %><em><%= link_to t("ruby_on_rails_tutorial"), Settings.railstutorials_org %></em>,<%= t "part_of_the" %>
  <%= link_to t("learn_enough"), Settings.learn_enough_tutorials %> <%= t "family_of_tutorials,_is_a" %>
  <%= link_to t("book"), Settings.tutorials_book %> <% t "and" %>
  <%= link_to t("screencast_series"), Settings.screencast_tutorials %>
  <%= t "to_teach_web_development_with" %>
  <%= link_to "Ruby on Rails", Settings.rubyonrails_org %>.
  <%= t "this_is_the_sample_app_for_the_tutorial" %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t("help") %>
<h1><%= t "help" %></h1>
<p>
  <%= t "get_help_on_the_ruby_on_rails_tutorial_at_the" %>
  <%= link_to t("rails_tutorial_help_page"), Settings.rails_help %>.
  <%= t "to_get_help_on_this_sample_app,_see_the" %><em><%= link_to t("ruby_on_rails_tutorial"),Settings.tutorials_book %></em> <%= t "book" %>
</p>

app/views/static_pages/home.html.erb
<% provide :title, t("home") %>
<div class="center jumbotron">
  <h1><%= t "welcome_to_the_sample_app" %></h1>
	<h2>
    <%= t "this_is_the_home_page_for_the" %>
  	<%= link_to t("ruby_on_rails_tutorial"), Settings.railstutorials_org %>
  	<%= t "sample_application" %>
	</h2>
	<%= link_to t("sign_up_now"), signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("/assets/rails.png", alt: "Rails logo"), Settings.rubyonrails_org %>

app/views/users/new.html.erb
<% provide :title, t("signup") %>
<h1> <%= t "sign_up" %> </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label t "name"  %>
      <%= f.text_field :name %>
      <%= f.label t "email" %>
      <%= f.email_field :email %>
      <%= f.label t "password" %>
      <%= f.password_field :password %>
      <%= f.label t "password_confirmation", t "confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit t "create_my_account", class: "btn btn-primary" %>
    <% end %>
   </div>
  </div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
     </section>
  </aside>
</div>